# Site settings
title: ThinkingRemote
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  ThinkingRemote is a place to learn and share information about working remotely and 
  telecommuting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: thinkingremote
github_username:  jekyll

# Build settings
markdown: kramdown

sass:
  sass_dir: css/_sass